config/routes.rb
Sdq::Application.routes.draw do
  
  resources :question_groups
  resources :questions
  resources :campaigns do
    match 'surveys/new/adult' => 'surveys#new', :group_category => 'adult', :as => :new_adult_survey
    match 'surveys/new/child' => 'surveys#new', :group_category => 'child', :as => :new_child_survey
    resources :surveys, :except => [:new, :edit, :index, :show, :destroy]
  end
  resources :surveys, :only => [:edit, :show, :destroy]
  
  resources :clients
  match 'clients/search' => 'clients#search'

  root :to => "campaigns#index"

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :surveys
  
  GENDERS = ['boy', 'girl']
  
  validates_presence_of :name
  validates_inclusion_of :gender, :in => self::GENDERS, :message => "can't be blank"
  validates_presence_of :born_on
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = Client.all
  end
  
  def show
    @client = Client.find(params[:id])
  end
  
  def edit
    @client = Client.find(params[:id])
  end
  
  def new
    @client = Client.new
  end
  
  def update
    @client = Client.find(params[:id])
    if @client.update_attributes(params[:client])
      redirect_to(@client, notice: 'Client was successfully updated.')
    else
      render action: :edit
    end
  end
  
  def create
    @client = Client.new(params[:client])
    if @client.save
      redirect_to(client_path(@client), :notice => 'Client was successfully created.')
    else
      render action: "new"
    end
  end
  
  def search
    conditions = []
    place_holders = {}
    
    if params[:client_search_name] != ''
      conditions << "name LIKE :name"
      place_holders[:name] = '%' + params[:client_search_name] + '%'
    end
    
    if params[:client_search_dob] != ''
      conditions << "born_on = :dob"
      place_holders[:dob] = params[:client_search_dob]
    end
    
    if params[:client_search_gender] != ''
      conditions << "gender = :gender"
      place_holders[:gender] = params[:client_search_gender]
    end
    
    @clients = Client.where(conditions.join(' AND '), place_holders)

    respond_to do |format|
      format.js {render :layout => false}
    end
  end
  
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.haml
%div
  = client.name
  = client.born_on
  %span{:id => "survey_client_selector_#{client.id}"} Select
  = hidden_field_tag "survey_client_selector_name_#{client.id}", client.name

app/views/clients/_form.haml
= form_for @client do |f|
  - if @client.errors.any?
    %div#error_explanation
      %h2= "#{pluralize(@client.errors.count, "error")} prohibited this client from being saved:"
      %ul
        - @client.errors.full_messages.each do |msg|
          %li= msg

  %p
    = f.label :name
    %br/
    = f.text_field :name
  
  %p
    = f.label :born_on, "Date of birth"
    %br/
    = f.text_field :born_on

  %p
    = f.label :gender
    %br/
    = f.select :gender, Client::GENDERS.map {|g| [g.humanize, g]}, :include_blank => :true

  %p.action
    %span.no-action= link_to "Cancel", @client
    = f.submit

app/views/clients/edit.haml
%h1 Edit Client

= render 'form'

app/views/clients/index.haml
%h1 List of Clients

%div.menu
  = link_to "New Client", new_client_path

%table.index
  %tr.header
    %th Name
    %th Date of Birth
    %th Gender
    %th &nbsp;
  - @clients.each do |client|
    %tr{:class => cycle('odd', 'even')}
      %td= client.name
      %td= client.born_on
      %td= client.gender.humanize
      %td= link_to "View", client

app/views/clients/new.haml
%h1 New Client

= render 'form'

app/views/clients/search.js.erb
$.getScript('/javascripts/client-search-results.js');
$('#client_search_result').html("<%= escape_javascript(render(@clients)) %>");

app/views/clients/show.haml
%h1 Client Details

%div.menu
  = link_to "Back to clients", clients_path
  %span.right
    = link_to "Edit", edit_client_path(@client)


%p
  %b Name:
  = @client.name

%p
  %b Date of birth:
  = @client.born_on

%p
  %b Gender:
  = @client.gender.humanize

%h2 Surveys

%table.index
  %tr.header
    %th Date
    %th Campaign
    %th Completed by
    %th Score
    %th &nbsp;
  - @client.surveys.each do |survey|
    %tr{:class => cycle('odd', 'even')}
      %td= survey.created_at
      %td= link_to survey.campaign.name, survey.campaign
      %td= survey.category.humanize
      %td= "#{ScoreRange.survey_score(survey.category, survey.score)} (#{survey.score})"
      %td= link_to "View", survey