config/routes.rb
Sdq::Application.routes.draw do
  
  resources :question_groups
  resources :questions
  resources :campaigns do
    match 'surveys/new/adult' => 'surveys#new', :group_category => 'adult', :as => :new_adult_survey
    match 'surveys/new/child' => 'surveys#new', :group_category => 'child', :as => :new_child_survey
    resources :surveys, :except => [:new, :edit, :index, :show, :destroy]
  end
  resources :surveys, :only => [:edit, :show, :destroy]
  
  resources :clients
  match 'clients/search' => 'clients#search'

  root :to => "campaigns#index"

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :client
  belongs_to :campaign
  has_many :answers, :dependent => :destroy
  
  validates_presence_of :category, :message => "Please, tell us who you are"
  validates_presence_of :client, :message => "Select a client"
  accepts_nested_attributes_for :answers
  
  after_create :set_total_score
  before_update :update_total_score

  CATEGORIES = {
    :adult => ['parent', 'teacher'],
    :child => ['child']
  } 

  def group_category
    Survey::CATEGORIES.each_pair do |key, value|
      return key.to_s if value.include?(self.category)
    end
  end
  
  def find_answer(question_id)
    if self.answers.empty?
      return Answer.new
    else
      self.answers.each do |a|
        return a if (a.question_id == question_id)
      end
    end
  end
  
  def group_scores
    return @group_scores if defined?(@group_scores)
    @group_scores = {}

    QuestionGroup.where("question_groups.category = '#{self.group_category}'").each do |g|
      @group_scores[g.id] = 0
     end

    self.answers.includes(:question, :option).each do |a|
      @group_scores[a.question.question_group.id] += a.option.weight
    end
    @group_scores
  end
  
  private
  
  def set_total_score
    update_total_score
    save
  end
  
  def update_total_score
    s = 0
    self.answers.includes(:option).each  {|a| s += a.option.weight}
    self.score = s
  end
  
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    @surveys = Survey.order("created_at DESC")
  end
  
  def show
    @survey = Survey.find(params[:id])
    @groups = QuestionGroup.includes(:questions).where("question_groups.category = '#{@survey.group_category}'").order("sequence ASC")
  end
  
  def new
    @campaign = Campaign.find(params[:campaign_id])
    @survey = Survey.new(:campaign => @campaign)
    @group_category = params[:group_category]
    @questions = Question.find_by_group_category(@group_category).includes(:options).order("sequence_global ASC")
  end
  
  def create
    @campaign = Campaign.find(params[:campaign_id])
    @survey = Survey.new(params[:survey])
    @survey.campaign = @campaign
    @group_category = params[:group_category]
    if @survey.save
      redirect_to(campaign_path(@campaign), :notice => 'Survey was successfully created.')
    else
      @questions = Question.find_by_group_category(@group_category).includes(:options).order("sequence_global ASC")
      render action: "new"
    end
  end
  
  def edit
    @survey = Survey.find(params[:id])
    @campaign = @survey.campaign
    @group_category = @survey.group_category
    @questions = Question.find_by_group_category(@group_category).includes(:options).order("sequence_global ASC")
  end
  
  def update
    @campaign = Campaign.find(params[:campaign_id])
    @survey = Survey.find(params[:id])
    @group_category = @survey.group_category
    if @survey.update_attributes(params[:survey])
      redirect_to(@survey, notice: 'Survey was successfully updated.')
    else
      @questions = Question.find_by_group_category(@group_category).includes(:options).order("sequence_global ASC")
      render action: :edit
    end
  end
  
  def destroy
    @survey = Survey.find(params[:id])
    campaign = @survey.campaign
    @survey.destroy
    redirect_to(campaign_url(campaign))
  end
  
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.haml
%div#modal-client{:title => "Assign Client To Survey"}
  = render 'search_client'
  %div#client_search_result

%p{:id => "boubou"}

= form_for([@campaign, @survey]) do |f|
  - if @survey.errors.any?
    %div#error_explanation
      %h2= "#{pluralize(@survey.errors.count, "error")} prohibited this survey from being saved:"
      %ul
        - @survey.errors.full_messages.each do |msg|
          %li= msg
  %p
    %b Campaign:
    = @campaign.name
    
  %p
    %b Client: 
    %span{:id => "client-name"}= @survey.client.name if @survey.client
    - if @survey.client
      = link_to "Change", "#", :id => "button-modal-client"
    - else
      = link_to "Search", "#", :id => "button-modal-client"
    
  %p
    = f.label :category, "Please, tell us you you are"
    %br/
    = f.select :category, Survey::CATEGORIES[@group_category.to_sym].map {|c| [c.humanize, c]}, include_blank: :true
  
  %table.survey
    %tr.header
      %th
      %th.option-label
        Not
        %br/
        True
      %th.option-label
        Somewhat
        %br/
        True
      %th.option-label
        Certainly
        %br/
        True
    - @questions.each do |q|
      %tr{:class => cycle('odd', 'even')}
        %td= q.label
        = f.fields_for :answers, @survey.find_answer(q.id) do |answer|
          - q.options.each do |o|
            %td.info
              = answer.radio_button :option_id, o.id
          = answer.hidden_field :question_id, value: q.id
    %tr
      %td.action{:colspan => 4}
        %span.no-action= @survey.id ? link_to("Cancel", @survey) : link_to("Cancel", @campaign)
        = f.submit
  = hidden_field_tag :group_category, @group_category
  = f.hidden_field :client_id

app/views/surveys/_search_client.haml
= form_tag({:controller => "clients", :action => "search"}, :remote => :true) do
  %p
    = label_tag :client_search_name, "Name: "
    = text_field_tag :client_search_name
  
  %p
    = label_tag :client_search_gender, "Gender: "
    = select_tag(:client_search_gender, options_for_select(Client::GENDERS.map {|g| [g.humanize, g]}), :include_blank => :true)

  %p
    = label_tag :client_search_dob, "Date of birth: "
    = text_field_tag :client_search_dob

  %p= submit_tag "Search"
  

%span#new-client-button-search
  New client

%div#client-new-fields-search
  %p
    = label_tag :client_new_name_search, "Name: "
    = text_field_tag :client_new_name_search
    
  %p
    = label_tag :client_new_gender_search, "Gender: "
    = select_tag :client_new_gender_search, options_for_select(Client::GENDERS.map {|g| [g.humanize, g]}), :include_blank => true

  %p
    = label_tag :client_new_dob_search, "Date of birth: "
    = text_field_tag :client_new_dob_search

app/views/surveys/edit.haml
%h1 Edit SDQ Survey

= render 'form'

app/views/surveys/index.haml
%h1 List Of SDQ Surveys

%div.menu
  = link_to("New Adult Survey", new_adult_survey_path) + " | "
  = link_to("New Child Survey", new_child_survey_path)

%br/

%table.index
  %tr.header
    %th Date
    %th Category
    %th Score
    %th
  - @surveys.each do |s|
    %tr{:class => cycle('odd', 'even')}
      %td= s.created_at
      %td= s.category.humanize
      %td= "#{ScoreRange.survey_score(s.category, s.score)} (#{s.score})"
      %td= link_to "View", s

app/views/surveys/new.haml
%h1 New SDQ Survey

= render 'form'

app/views/surveys/show.haml
%h1 SDQ Survey Details

%div.menu
  %span.left
    = link_to "Back to campaign", campaign_path(@survey.campaign)
  %span.right
    = link_to("Edit", edit_survey_path(@survey)) + " | "
    = link_to('Destroy', @survey, :confirm => 'Are you sure?', :method => :delete)

%p
  %b Campaign: 
  = @survey.campaign.name

%p
  %b Client:
  = @survey.client.name

%p
  Completed by a
  %u= @survey.category.humanize
  on
  = @survey.created_at

%table.survey
  - @groups.each do |g|
    %tr.question-group
      %th.group-label= g.label
      %th.option-label
        Not
        %br/
        True
      %th.option-label
        Somewhat
        %br/
        True
      %th.option-label
        Certainly
        %br/
        True
    - g.questions.order("sequence_group").each do |q|
      %tr{:class => cycle('even', 'odd', :name => "row_colors")}
        %td= q.label
        - answer = @survey.find_answer(q.id)
        - q.options.each do |o|
          %td.info= "X" if o.id == answer.option_id
    %tr.group-score
      %td.score-label Score
      %td.score-value{:colspan => 3}
        = "#{ScoreRange.group_score(g.id, @survey.category, @survey.group_scores[g.id])} (#{@survey.group_scores[g.id]})"
    %tr
      %td{:colspan => 4} &nbsp;
      - reset_cycle("row_colors")
  %tr.total-score
    %td.score-label Total Difficulties Score
    %td.score-value{:colspan => 3}= "#{ScoreRange.survey_score(@survey.category, @survey.score)} (#{@survey.score})"