config/routes.rb
Sdq::Application.routes.draw do
  
  resources :question_groups
  resources :questions
  resources :campaigns do
    match 'surveys/new/adult' => 'surveys#new', :group_category => 'adult', :as => :new_adult_survey
    match 'surveys/new/child' => 'surveys#new', :group_category => 'child', :as => :new_child_survey
    resources :surveys, :except => [:new, :edit, :index, :show, :destroy]
  end
  resources :surveys, :only => [:edit, :show, :destroy]
  
  resources :clients
  match 'clients/search' => 'clients#search'

  root :to => "campaigns#index"

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :surveys, dependent: :destroy
  
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :description
  validates_presence_of :starts_on
  validates_presence_of :ends_on
  
  validate :ends_on_after_start_date
  
  def ends_on_after_start_date
    errors[:base] << "End date must be posterior to Start date" if ends_on < starts_on
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def index
    @campaigns = Campaign.all
  end

  def show
    @campaign = Campaign.find(params[:id])
  end
  
  def new
    @campaign = Campaign.new
  end
  
  def create
    @campaign = Campaign.new(params[:campaign])
    if @campaign.save
      redirect_to(campaigns_path, :notice => 'Campaign was successfully created.')
    else
      render action: "new"
    end
  end
  
  def edit
    @campaign = Campaign.find(params[:id])
  end
  
  def update
    @campaign = Campaign.find(params[:id])
    if @campaign.update_attributes(params[:campaign])
      redirect_to(@campaign, :notice => 'Campaign was successfully updated.')
    else
      render action: "edit"
    end
  end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.haml
= form_for(@campaign) do |f|
  - if @campaign.errors.any?
    %div#error_explanation
      %h2= "#{pluralize(@campaign.errors.count, "error")} prohibited this survey from being saved:"
      %ul
        - @campaign.errors.full_messages.each do |msg|
          %li= msg
  
  %p
    = f.label :name
    %br/
    = f.text_field :name
  
  %p
    = f.label :starts_on, "Start date"
    %br/
    = f.text_field :starts_on
    
  %p
    = f.label :ends_on, "End date"
    %br/
    = f.text_field :ends_on
  
  %p
    = f.label :description
    %br/
    = f.text_area :description

  %p.action
    %span.no-action= link_to "Cancel", @campaign
    = f.submit

app/views/campaigns/edit.haml
%h1 Edit Campaign

= render 'form'

app/views/campaigns/index.haml
%h1 List of Campaigns

%div.menu
  = link_to("New Campaign", new_campaign_path)

%br/

%table.index
  %tr.header
    %th Name
    %th Start Date
    %th End Date
    %th
  - @campaigns.each do |c|
    %tr{:class => cycle('odd', 'even')}
      %td= c.name
      %td= c.starts_on
      %td= c.ends_on
      %td= link_to "View", c

app/views/campaigns/new.haml
%h1 New Campaign

= render 'form'

app/views/campaigns/show.haml
%h1= "Campaign - #{@campaign.name}"

%div.menu
  = link_to "Back to Campaigns", campaigns_path
  %span.right
    = link_to("Edit", edit_campaign_path(@campaign)) + " | "
    = link_to('Destroy', @campaign, :confirm => 'Are you sure?', :method => :delete)

%h2 Details

%p
  %b Start date:
  = @campaign.starts_on

%p
  %b End date:
  = @campaign.ends_on

%p
  %b Description:
  %br/
  = @campaign.description


%h2 Surveys

%div.menu
  = link_to("New Adult Survey", campaign_new_adult_survey_path(@campaign)) + " | "
  = link_to "New Child Survey", campaign_new_child_survey_path(@campaign)

%table.index
  %tr.header
    %th Date
    %th Client
    %th Completed by
    %th Score
    %th &nbsp;
  - @campaign.surveys.each do |s|
    %tr{:class => cycle('odd', 'even')}
      %td= s.created_at
      %td= link_to s.client.name, s.client
      %td= s.category.humanize
      %td= "#{ScoreRange.survey_score(s.category, s.score)} (#{s.score})"
      %td= link_to "View", survey_path(s)